### PR TITLE
Avoid stop poll loop (optionally)

### PR DESCRIPTION
**Pull request by tehnick**

### CODE REVIEW

**Comment by monich** [comment]
Out of curiosity, what kind of scenario is that supposed to help with?

**Comment by tehnick** [comment]
It is for having permanently running process in specified nfc mode.

**Comment by monich** [comment]
But this doesn't stop NFC mode from being manipulated by other plugins.

If looks as if you're trying to do something very neard specific - but not clear exactly what, that's why I asked. Disabling neard plugin altogether isn't an option, I guess.

**Comment by tehnick** [comment]
Yep, you are right. Probably this change is not useful for upstream.

**Pull request closed without merging**
