### PR TITLE
Link with libnfcdef

### PR DESCRIPTION
**Pull request by monich**
NDEF build and parse functionality makes sense outside of nfcd plugin context. ndef-write tool is one example of that.

This requires integration of [libnfcdef](https://github.com/monich/libnfcdef) into Sailfish OS.

### CODE REVIEW

**Review by mlehtima — APPROVED** [review]

**Comment by monich** [comment]
[libnfcdef](https://github.com/monich/libnfcdef) needs to be integrated first or else the build will fail. AFAICT it's not done yet. Or is it?

**Comment by mlehtima** [comment]
> [libnfcdef](https://github.com/monich/libnfcdef) needs to be integrated first or else the build will fail. AFAICT it's not done yet. Or is it?

It is not done yet.

**Comment by monich** [comment]
> It is not done yet.

Is there any hope to get it done any time soon? I have quite a few changes in the pipeline on top of this one (such as support for card emulation)

**Comment by monich** [comment]
> Is there any hope to get it done any time soon? I have quite a few changes in the pipeline on top of this one (such as support for card emulation)

if there's no hope then I'll create a branch (called e.g. `next`) and continue development there 😐

**Comment by monich** [comment]
I'll merge this one but won't tag it until [libnfcdef](https://github.com/monich/libnfcdef) gets integrated.

**Comment by monich** [comment]
A funny thing is that I actually have github permissions to create new repos in https://github.com/mer-hybris, it's just that I think that [libnfcdef](https://github.com/monich/libnfcdef) doesn't belong there because it's a very generic thing, not related to any hardware adaptation at all 😐

**Pull request merged**
